Repository schier-brothers/DnDeep-backend, pull requests merged in 2020-02, with the labels that each got.

#5 Added MVP-1 information map
  informationMap/MVP-1.dia
  informationMap/MVP-1.png
Labels: Todo

#6 Git fix
  .gitignore
Labels: help wanted

#13 Feature/ci and environment
  .jshintrc
  .travis.yml
  README.md
  app.js
  auth/google.js
  bin/www
  models/User.js
  package-lock.json
  package.json
Labels: enhancement

#10 Feature/char model
  README.md
  app.js
  models/Character.js
  models/CharacterClass.js
  models/Race.js
  package.json
  routes/auth.js
  routes/characters.js
  routes/index.js
  routes/users.js
Labels: documentation, enhancement

#17 Moved character functions to characterService with dependency injection
  .eslintrc.json
  .vscode/launch.json
  README.md
  models/Character.js
  models/Race.js
  package-lock.json
  package.json
  routes/characters.js
  services/characterService.js
Labels: refactor, refine
